package com.example.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * 数据库备份工具类
 * 使用纯Java方式备份数据库，不依赖外部命令
 */
@Slf4j
@Component
public class DatabaseBackupUtil {
    
    /**
     * 备份数据库到文件
     * 
     * @param connection 数据库连接
     * @param outputFile 输出文件路径
     * @param databaseName 数据库名称
     * @throws Exception 备份异常
     */
    public void backupDatabase(Connection connection, String outputFile, String databaseName) throws Exception {
        log.info("开始备份数据库: {}", databaseName);
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile))) {
            // 写入备份文件头部信息
            writeHeader(writer, databaseName);
            
            // 获取所有表
            List<String> tables = getTables(connection, databaseName);
            log.info("找到 {} 个表", tables.size());
            
            // 备份每个表
            for (String table : tables) {
                log.info("备份表: {}", table);
                backupTable(connection, writer, table);
            }
            
            // 写入备份文件尾部信息
            writeFooter(writer);
            
            log.info("数据库备份完成: {}", outputFile);
        }
    }
    
    /**
     * 写入备份文件头部
     */
    private void writeHeader(BufferedWriter writer, String databaseName) throws IOException {
        writer.write("-- MySQL Database Backup\n");
        writer.write("-- Generated by Cultural Relics Management System\n");
        writer.write("-- Date: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + "\n");
        writer.write("-- Database: " + databaseName + "\n");
        writer.write("-- ------------------------------------------------------\n\n");
        
        writer.write("SET NAMES utf8mb4;\n");
        writer.write("SET FOREIGN_KEY_CHECKS = 0;\n\n");
        
        writer.write("DROP DATABASE IF EXISTS `" + databaseName + "`;\n");
        writer.write("CREATE DATABASE `" + databaseName + "` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n");
        writer.write("USE `" + databaseName + "`;\n\n");
    }
    
    /**
     * 写入备份文件尾部
     */
    private void writeFooter(BufferedWriter writer) throws IOException {
        writer.write("\n-- ------------------------------------------------------\n");
        writer.write("-- Backup completed\n");
        writer.write("SET FOREIGN_KEY_CHECKS = 1;\n");
    }
    
    /**
     * 获取数据库中的所有表
     */
    private List<String> getTables(Connection connection, String databaseName) throws SQLException {
        List<String> tables = new ArrayList<>();
        
        String sql = "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE'";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, databaseName);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    tables.add(rs.getString("TABLE_NAME"));
                }
            }
        }
        
        return tables;
    }
    
    /**
     * 备份单个表
     */
    private void backupTable(Connection connection, BufferedWriter writer, String tableName) throws Exception {
        // 1. 获取表结构
        String createTableSQL = getCreateTableSQL(connection, tableName);
        writer.write("-- ----------------------------\n");
        writer.write("-- Table structure for " + tableName + "\n");
        writer.write("-- ----------------------------\n");
        writer.write("DROP TABLE IF EXISTS `" + tableName + "`;\n");
        writer.write(createTableSQL + ";\n\n");
        
        // 2. 获取表数据
        writer.write("-- ----------------------------\n");
        writer.write("-- Records of " + tableName + "\n");
        writer.write("-- ----------------------------\n");
        
        String selectSQL = "SELECT * FROM `" + tableName + "`";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(selectSQL)) {
            
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            // 获取列名
            List<String> columnNames = new ArrayList<>();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }
            
            // 写入数据
            int rowCount = 0;
            while (rs.next()) {
                if (rowCount == 0) {
                    writer.write("INSERT INTO `" + tableName + "` (");
                    for (int i = 0; i < columnNames.size(); i++) {
                        if (i > 0) writer.write(", ");
                        writer.write("`" + columnNames.get(i) + "`");
                    }
                    writer.write(") VALUES\n");
                }
                
                if (rowCount > 0) {
                    writer.write(",\n");
                }
                
                writer.write("(");
                for (int i = 1; i <= columnCount; i++) {
                    if (i > 0) writer.write(", ");
                    
                    Object value = rs.getObject(i);
                    if (value == null) {
                        writer.write("NULL");
                    } else if (value instanceof String || value instanceof Date || value instanceof Timestamp) {
                        // 字符串和日期类型需要加引号，并转义特殊字符
                        String strValue = value.toString();
                        strValue = strValue.replace("\\", "\\\\")
                                         .replace("'", "\\'")
                                         .replace("\n", "\\n")
                                         .replace("\r", "\\r");
                        writer.write("'" + strValue + "'");
                    } else {
                        writer.write(value.toString());
                    }
                }
                writer.write(")");
                
                rowCount++;
                
                // 每1000行提交一次，避免SQL语句过长
                if (rowCount % 1000 == 0) {
                    writer.write(";\n\n");
                    writer.write("INSERT INTO `" + tableName + "` (");
                    for (int i = 0; i < columnNames.size(); i++) {
                        if (i > 0) writer.write(", ");
                        writer.write("`" + columnNames.get(i) + "`");
                    }
                    writer.write(") VALUES\n");
                    rowCount = 0;
                }
            }
            
            if (rowCount > 0) {
                writer.write(";\n");
            }
            
            writer.write("\n");
        }
    }
    
    /**
     * 获取创建表的SQL语句
     */
    private String getCreateTableSQL(Connection connection, String tableName) throws SQLException {
        String sql = "SHOW CREATE TABLE `" + tableName + "`";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            if (rs.next()) {
                return rs.getString(2);
            }
        }
        throw new SQLException("无法获取表结构: " + tableName);
    }
    
    /**
     * 从备份文件恢复数据库
     * 
     * @param connection 数据库连接
     * @param backupFile 备份文件路径
     * @throws Exception 恢复异常
     */
    public void restoreDatabase(Connection connection, String backupFile) throws Exception {
        log.info("开始恢复数据库: {}", backupFile);
        
        try (BufferedReader reader = new BufferedReader(new FileReader(backupFile))) {
            StringBuilder sqlBuilder = new StringBuilder();
            String line;
            int executedCount = 0;
            
            while ((line = reader.readLine()) != null) {
                // 跳过注释和空行
                line = line.trim();
                if (line.isEmpty() || line.startsWith("--")) {
                    continue;
                }
                
                sqlBuilder.append(line).append("\n");
                
                // 如果遇到分号，执行SQL
                if (line.endsWith(";")) {
                    String sql = sqlBuilder.toString();
                    try (Statement stmt = connection.createStatement()) {
                        stmt.execute(sql);
                        executedCount++;
                        
                        if (executedCount % 100 == 0) {
                            log.info("已执行 {} 条SQL语句", executedCount);
                        }
                    } catch (SQLException e) {
                        log.warn("执行SQL失败: {}", sql.substring(0, Math.min(100, sql.length())), e);
                        // 继续执行其他SQL
                    }
                    sqlBuilder.setLength(0);
                }
            }
            
            log.info("数据库恢复完成，共执行 {} 条SQL语句", executedCount);
        }
    }
}
