/**
 * 生成简单的3D模型数据（用于测试）
 * 可以生成GLTF格式的JSON数据
 */

/**
 * 生成一个简单的立方体GLTF模型
 */
export function generateCubeGLTF() {
  return {
    asset: {
      version: "2.0",
      generator: "Cultural Relics 3D Generator"
    },
    scene: 0,
    scenes: [
      {
        nodes: [0]
      }
    ],
    nodes: [
      {
        mesh: 0
      }
    ],
    meshes: [
      {
        primitives: [
          {
            attributes: {
              POSITION: 0,
              NORMAL: 1
            },
            indices: 2
          }
        ]
      }
    ],
    accessors: [
      {
        bufferView: 0,
        componentType: 5126,
        count: 24,
        type: "VEC3",
        max: [1, 1, 1],
        min: [-1, -1, -1]
      },
      {
        bufferView: 1,
        componentType: 5126,
        count: 24,
        type: "VEC3"
      },
      {
        bufferView: 2,
        componentType: 5123,
        count: 36,
        type: "SCALAR"
      }
    ],
    bufferViews: [
      {
        buffer: 0,
        byteOffset: 0,
        byteLength: 288,
        target: 34962
      },
      {
        buffer: 0,
        byteOffset: 288,
        byteLength: 288,
        target: 34962
      },
      {
        buffer: 0,
        byteOffset: 576,
        byteLength: 72,
        target: 34963
      }
    ],
    buffers: [
      {
        byteLength: 648,
        uri: "data:application/octet-stream;base64,..." // 这里需要实际的二进制数据
      }
    ]
  }
}

/**
 * 生成一个简单的球体GLTF模型
 */
export function generateSphereGLTF() {
  // 简化版本，实际应用中需要更复杂的几何数据
  return {
    asset: {
      version: "2.0",
      generator: "Cultural Relics 3D Generator"
    },
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0 }],
    meshes: [
      {
        primitives: [
          {
            attributes: {
              POSITION: 0,
              NORMAL: 1
            },
            indices: 2
          }
        ]
      }
    ]
  }
}

/**
 * 生成OBJ格式的立方体模型
 */
export function generateCubeOBJ() {
  return `# Cube OBJ File
# Generated by Cultural Relics 3D Generator

v -1.0 -1.0  1.0
v  1.0 -1.0  1.0
v  1.0  1.0  1.0
v -1.0  1.0  1.0
v -1.0 -1.0 -1.0
v  1.0 -1.0 -1.0
v  1.0  1.0 -1.0
v -1.0  1.0 -1.0

vn  0.0  0.0  1.0
vn  0.0  0.0 -1.0
vn  0.0  1.0  0.0
vn  0.0 -1.0  0.0
vn  1.0  0.0  0.0
vn -1.0  0.0  0.0

f 1//1 2//1 3//1 4//1
f 5//2 8//2 7//2 6//2
f 1//3 4//3 8//3 5//3
f 2//4 6//4 7//4 3//4
f 4//5 3//5 7//5 8//5
f 1//6 5//6 6//6 2//6
`
}

/**
 * 创建一个Blob URL用于预览
 */
export function createModelBlobUrl(modelData, type = 'gltf') {
  let blob
  if (type === 'gltf') {
    blob = new Blob([JSON.stringify(modelData)], { type: 'model/gltf+json' })
  } else if (type === 'obj') {
    blob = new Blob([modelData], { type: 'text/plain' })
  }
  return URL.createObjectURL(blob)
}

/**
 * 下载模型文件
 */
export function downloadModel(modelData, filename, type = 'gltf') {
  let content
  let mimeType
  
  if (type === 'gltf') {
    content = JSON.stringify(modelData, null, 2)
    mimeType = 'model/gltf+json'
  } else if (type === 'obj') {
    content = modelData
    mimeType = 'text/plain'
  }
  
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}
